{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggpattern
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggpattern_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggpattern/ggpattern_{{ version }}.tar.gz
  sha256: f9652a22bfd041ace5fd99a499d1e4f15bf2aa34d7a1f2571af911f368772bad

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-glue
    - r-gridpattern >=0.5.1
    - r-rlang
    - r-scales
  run:
    - r-base
    - r-ggplot2
    - r-glue
    - r-gridpattern >=0.5.1
    - r-rlang
    - r-scales

test:
  commands:
    - $R -e "library('ggpattern')"           # [not win]
    - "\"%R%\" -e \"library('ggpattern')\""  # [win]

about:
  home: https://github.com/coolbutuseless/ggpattern, https://coolbutuseless.github.io/package/ggpattern/index.html
  license: MIT
  summary: Provides 'ggplot2' geoms filled with various patterns.  Includes a patterned version of every 'ggplot2' geom that has a region that can be filled with a pattern.  Provides a suite of 'ggplot2' aesthetics and scales for controlling pattern appearances.  Supports over a dozen builtin patterns (every pattern implemented
    by 'gridpattern') as well as allowing custom user-defined patterns.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
